local config = require("config")

local function reset_settings()
    config._reset_for_test()
    for k in pairs(_G._test_settings_data) do
        _G._test_settings_data[k] = nil
    end
end

describe("config defensive guards", function()
    before_each(function()
        reset_settings()
    end)

    describe("addDomain", function()
        it("rejects nil without crashing", function()
            config.addDomain("example.com")
            config.addDomain(nil)
            assert.same({ "example.com" }, config.getDomains())
        end)

        it("rejects empty string without adding it", function()
            config.addDomain("example.com")
            config.addDomain("")
            assert.same({ "example.com" }, config.getDomains())
        end)

        it("rejects non-string (number) without crashing", function()
            config.addDomain(123)
            assert.same({}, config.getDomains())
        end)

        it("rejects non-string (table) without crashing", function()
            config.addDomain({})
            assert.same({}, config.getDomains())
        end)
    end)

    describe("removeDomain", function()
        it("rejects nil without crashing", function()
            config.addDomain("a.com")
            config.addDomain("b.com")
            config.removeDomain(nil)
            assert.same({ "a.com", "b.com" }, config.getDomains())
        end)

        it("rejects empty string without crashing", function()
            config.addDomain("a.com")
            config.removeDomain("")
            assert.same({ "a.com" }, config.getDomains())
        end)
    end)

    describe("setLogLevel", function()
        it("returns false for nil without crashing", function()
            config.setLogLevel("dbg")
            local ok = config.setLogLevel(nil)
            assert.is_false(ok)
            assert.equals("dbg", config.getLogLevel())
        end)

        it("returns false for invalid level name", function()
            config.setLogLevel("warn")
            local ok = config.setLogLevel("LOUD")
            assert.is_false(ok)
            assert.equals("warn", config.getLogLevel())
        end)

        it("returns false for non-string (number)", function()
            config.setLogLevel("info")
            local ok = config.setLogLevel(42)
            assert.is_false(ok)
            assert.equals("info", config.getLogLevel())
        end)
    end)

    describe("setDomains", function()
        it("sets to empty table when given nil", function()
            config.addDomain("example.com")
            config.setDomains(nil)
            assert.same({}, config.getDomains())
        end)

        it("sets to empty table when given non-table", function()
            config.addDomain("example.com")
            config.setDomains("not a table")
            assert.same({}, config.getDomains())
        end)
    end)

    describe("addCustomHeader", function()
        it("returns nil, err for nil rule", function()
            local idx, err = config.addCustomHeader(nil)
            assert.is_nil(idx)
            assert.truthy(err)
            assert.same({}, config.getCustomHeaders())
        end)
    end)
end)
