local log = require("lib.log")

describe("log", function()
    before_each(function()
        log.setLevel("dbg")
        log.clear()
    end)

    describe("level filtering", function()
        it("off drops everything", function()
            log.setLevel("off")
            log.err("error msg")
            log.warn("warn msg")
            log.info("info msg")
            log.dbg("dbg msg")
            assert.equals(0, #log.getEntries())
        end)

        it("err keeps only errors", function()
            log.setLevel("err")
            log.err("error msg")
            log.warn("warn msg")
            log.info("info msg")
            log.dbg("dbg msg")
            local entries = log.getEntries()
            assert.equals(1, #entries)
            assert.equals("err", entries[1].level)
            assert.equals("error msg", entries[1].message)
        end)

        it("warn keeps err and warn", function()
            log.setLevel("warn")
            log.err("e")
            log.warn("w")
            log.info("i")
            log.dbg("d")
            local entries = log.getEntries()
            assert.equals(2, #entries)
            assert.equals("err", entries[1].level)
            assert.equals("warn", entries[2].level)
        end)

        it("info keeps err, warn, info", function()
            log.setLevel("info")
            log.err("e")
            log.warn("w")
            log.info("i")
            log.dbg("d")
            assert.equals(3, #log.getEntries())
        end)

        it("dbg keeps everything", function()
            log.setLevel("dbg")
            log.err("e")
            log.warn("w")
            log.info("i")
            log.dbg("d")
            assert.equals(4, #log.getEntries())
        end)

        it("getLevel returns the current level", function()
            log.setLevel("warn")
            assert.equals("warn", log.getLevel())
            log.setLevel("off")
            assert.equals("off", log.getLevel())
        end)
    end)

    describe("lazy formatting", function()
        it("does not format when no args are given", function()
            log.setLevel("info")
            log.info("plain string with %s %d")
            local entries = log.getEntries()
            assert.equals(1, #entries)
            -- No args => no string.format, stored as-is
            assert.equals("plain string with %s %d", entries[1].message)
        end)

        it("does not call string.format when level drops the message", function()
            -- %d with a string arg would error if string.format were called.
            -- At level "off", the early return prevents this — no error.
            log.setLevel("off")
            log.info("value: %d", "not a number")
            assert.equals(0, #log.getEntries())

            -- At level "info", string.format IS called.
            log.setLevel("info")
            log.info("value: %d", 42)
            assert.equals("value: 42", log.getEntries()[1].message)
        end)
    end)

    describe("ring buffer", function()
        it("stores entries in order", function()
            log.info("first")
            log.warn("second")
            log.err("third")
            local entries = log.getEntries()
            assert.equals(3, #entries)
            assert.equals("first", entries[1].message)
            assert.equals("second", entries[2].message)
            assert.equals("third", entries[3].message)
        end)

        it("evicts oldest entries when capacity is exceeded", function()
            log.setCapacity(3)
            log.info("a")
            log.info("b")
            log.info("c")
            log.info("d")
            local entries = log.getEntries()
            assert.equals(3, #entries)
            assert.equals("b", entries[1].message)
            assert.equals("c", entries[2].message)
            assert.equals("d", entries[3].message)
        end)

        it("clear empties the buffer", function()
            log.info("a")
            log.info("b")
            log.clear()
            assert.equals(0, #log.getEntries())
        end)

        it("getEntries returns a copy, not the internal table", function()
            log.info("original")
            local e = log.getEntries()
            e[1].message = "mutated"
            -- Internal buffer must be unaffected
            assert.equals("original", log.getEntries()[1].message)
        end)

        it("setCapacity trims existing entries when shrinking", function()
            log.info("a")
            log.info("b")
            log.info("c")
            log.setCapacity(1)
            assert.equals(1, #log.getEntries())
            assert.equals("c", log.getEntries()[1].message)
        end)
    end)

    describe("redaction", function()
        it("redacts long hex strings (32+ chars)", function()
            log.info("token: %s", "abcdef0123456789abcdef0123456789")
            local entries = log.getEntries()
            assert.equals("token: <redacted>", entries[1].message)
        end)

        it("does not redact short hex strings (< 32 chars)", function()
            log.info("id: %s", "abcdef0123456789")
            local entries = log.getEntries()
            assert.equals("id: abcdef0123456789", entries[1].message)
        end)

        it("redacts long base64-ish strings (40+ chars)", function()
            local secret = string.rep("ABCD", 12) -- 48 chars
            log.info("secret: %s", secret)
            local entries = log.getEntries()
            assert.equals("secret: <redacted>", entries[1].message)
        end)

        it("redacts embedded in a longer message", function()
            log.info("host=example.com token=%s status=200",
                "abcdef0123456789abcdef0123456789")
            local entries = log.getEntries()
            assert.equals("host=example.com token=<redacted> status=200",
                entries[1].message)
        end)

        it("redact is exposed and usable directly", function()
            assert.equals("<redacted>", log.redact("abcdef0123456789abcdef0123456789"))
            assert.equals("normal text", log.redact("normal text"))
        end)
    end)
end)
